name: Project Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make-dir
        run: make -f Makefile.own dir
      - name: linux-build
        run: make -f Makefile.own build
      - name: make run
        run: make -f Makefile.own run
      - name: Linux CMake Build
        run: cmake . && make

  build-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      # - name: install-make
      #   run: choco install make cmake
      - name: make-directory
        run: make -f Makefile.own dir
      - name: windows-build
        run: make -f Makefile.own winbuild
      - name: Windows CMake Build
        run: cmake -G "MinGW Makefiles" && cmake . && make
